// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6e7c8265-545e-4347-aee1-04c99ee52d08";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onFeedNowChange();

String lastFeedText;
float foodWeight;
bool feedNow;
bool lowFoodAlert;
bool petDetectedCloud;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(lastFeedText, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(foodWeight, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(feedNow, READWRITE, ON_CHANGE, onFeedNowChange);
  ArduinoCloud.addProperty(lowFoodAlert, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(petDetectedCloud, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
